## Actividad 3_17: Regresión con RN. ¿Cuanto vale un portátil?
<div style="border-style:groove;border-width:thin;padding:10px">
Ya hemos hecho un ejercicio de clasificación con redes neuronales. Vamos a trabajar ahora con uno de regresión. En este caso es un dataset con datos de portátiles. 
</div>

<div style="border-style:groove;border-width:thin;padding:10px">
Debes hacer lo siguiente:
    <ol>
        <li>Carga el archivo "laptop_price.csv".</li>
        <li>Echa un vistazo a los datos. Corrige cosas si es necesario.</li>
        <li>Hay muchas columnas categóricas. Transfórmalas.</li>
        <li>Divide el dataset en conjuntos de training y de test.</li>
        <li>Soluciona el ejercicio con una red neuronal.</li>
    </ol>
</div>

In [2611]:
# Datos y preprocesamiento
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Modelos de Clasificación
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Modelos de Regresión
from sklearn.svm import SVR, LinearSVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from tensorflow import keras

# Métricas de Clasificación
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Métricas de Regresión
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

# Visualización
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración
import warnings
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8-darkgrid')

print("✅ Todas las librerías importadas correctamente")

✅ Todas las librerías importadas correctamente

In [2612]:

df_prices = pd.read_csv('laptop_price.csv', encoding='latin-1')

df_prices.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [2613]:
df_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

In [2614]:
df_prices['Weight'].unique()

array(['1.37kg', '1.34kg', '1.86kg', '1.83kg', '2.1kg', '2.04kg', '1.3kg',
       '1.6kg', '2.2kg', '0.92kg', '1.22kg', '0.98kg', '2.5kg', '1.62kg',
       '1.91kg', '2.3kg', '1.35kg', '1.88kg', '1.89kg', '1.65kg',
       '2.71kg', '1.2kg', '1.44kg', '2.8kg', '2kg', '2.65kg', '2.77kg',
       '3.2kg', '0.69kg', '1.49kg', '2.4kg', '2.13kg', '2.43kg', '1.7kg',
       '1.4kg', '1.8kg', '1.9kg', '3kg', '1.252kg', '2.7kg', '2.02kg',
       '1.63kg', '1.96kg', '1.21kg', '2.45kg', '1.25kg', '1.5kg',
       '2.62kg', '1.38kg', '1.58kg', '1.85kg', '1.23kg', '1.26kg',
       '2.16kg', '2.36kg', '2.05kg', '1.32kg', '1.75kg', '0.97kg',
       '2.9kg', '2.56kg', '1.48kg', '1.74kg', '1.1kg', '1.56kg', '2.03kg',
       '1.05kg', '4.4kg', '1.90kg', '1.29kg', '2.0kg', '1.95kg', '2.06kg',
       '1.12kg', '1.42kg', '3.49kg', '3.35kg', '2.23kg', '4.42kg',
       '2.69kg', '2.37kg', '4.7kg', '3.6kg', '2.08kg', '4.3kg', '1.68kg',
       '1.41kg', '4.14kg', '2.18kg', '2.24kg', '2.67kg', '2.14kg',
       '1.36kg', '2.25kg', '2.15kg', '2.19kg', '2.54kg', '3.42kg',
       '1.28kg', '2.33kg', '1.45kg', '2.79kg', '1.84kg', '2.6kg',
       '2.26kg', '3.25kg', '1.59kg', '1.13kg', '1.78kg', '1.10kg',
       '1.15kg', '1.27kg', '1.43kg', '2.31kg', '1.16kg', '1.64kg',
       '2.17kg', '1.47kg', '3.78kg', '1.79kg', '0.91kg', '1.99kg',
       '4.33kg', '1.93kg', '1.87kg', '2.63kg', '3.4kg', '3.14kg',
       '1.94kg', '1.24kg', '4.6kg', '4.5kg', '2.73kg', '1.39kg', '2.29kg',
       '2.59kg', '2.94kg', '1.14kg', '3.8kg', '3.31kg', '1.09kg',
       '3.21kg', '1.19kg', '1.98kg', '1.17kg', '4.36kg', '1.71kg',
       '2.32kg', '4.2kg', '1.55kg', '0.81kg', '1.18kg', '2.72kg',
       '1.31kg', '0.920kg', '3.74kg', '1.76kg', '1.54kg', '2.83kg',
       '2.07kg', '2.38kg', '3.58kg', '1.08kg', '2.20kg', '2.75kg',
       '1.70kg', '2.99kg', '1.11kg', '2.09kg', '4kg', '3.0kg', '0.99kg',
       '3.52kg', '2.591kg', '2.21kg', '3.3kg', '2.191kg', '2.34kg',
       '4.0kg'], dtype=object)

In [2615]:
df_prices.drop(columns=['laptop_ID', 'Product'], inplace=True)

In [2616]:
for index, value in df_prices['Weight'].items():
    df_prices.at[index, 'Weight'] = float(value.replace('kg', '').strip())

In [2617]:
for index, value in df_prices['Ram'].items():
    df_prices.at[index, 'Ram'] = int(value.replace('GB', '').strip())

In [2618]:
df_prices['Ram'] = df_prices['Ram'].astype(int)
df_prices['Weight'] = df_prices['Weight'].astype(float)

In [2619]:
df_prices.corr(numeric_only=True)['Price_euros'].abs().sort_values(ascending=False)[1:]

Ram       0.743007
Weight    0.210370
Inches    0.068197
Name: Price_euros, dtype: float64

In [2620]:
df_prices = pd.get_dummies(df_prices, dtype=int)

In [2621]:
df_prices.head()

,Inches,Ram,Weight,Price_euros,Company_Acer,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,...,Gpu_Nvidia Quadro M620M,OpSys_Android,OpSys_Chrome OS,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS
0,13.3,8,1.37,1339.69,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,13.3,8,1.34,898.94,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,15.6,8,1.86,575.00,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,15.4,16,1.83,2537.45,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,13.3,8,1.37,1803.60,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [2622]:
X = df_prices.drop(columns=['Price_euros'])
y = df_prices['Price_euros']

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [2623]:
X_train_full, X_test, y_train_full, y_test = train_test_split(
X, y, test_size=0.1, random_state=0)

X_train, X_valid, y_train, y_valid = train_test_split(
X_train_full, y_train_full, test_size=0.1, random_state=0)

In [2624]:
model = keras.models.Sequential([
keras.layers.Dense(210, activation="relu", input_shape=X_train.shape[1:]),
keras.layers.Dense(140, activation="relu"),
keras.layers.Dense(1)
])

model.compile(loss="mean_absolute_error", optimizer="sgd",metrics=['mae'])

In [2625]:
history = model.fit(X_train, y_train, epochs=300,
validation_data=(X_valid, y_valid))

mse_test = model.evaluate(X_test, y_test)

Epoch 1/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1089.3641 - mae: 1089.3641 - val_loss: 1079.7389 - val_mae: 1079.7389
Epoch 2/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 613.7023 - mae: 613.7023 - val_loss: 337.8569 - val_mae: 337.8569
Epoch 3/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 267.6776 - mae: 267.6776 - val_loss: 262.7666 - val_mae: 262.7666
Epoch 4/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 215.8203 - mae: 215.8203 - val_loss: 264.5510 - val_mae: 264.5510
Epoch 5/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 195.3153 - mae: 195.3153 - val_loss: 253.1683 - val_mae: 253.1683
Epoch 6/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 188.2505 - mae: 188.2505 - val_loss: 290.8028 - val_mae: 290.8028
Epoch 7/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 180.6861 - mae: 180.6861 - val_loss: 231.5653 - val_mae: 231.5653
Epoch 8/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 191.2650 - mae: 191.2650 - val_loss: 238.2807 - val_mae: 238.2807
Epoch 9/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 185.7917 - mae: 185.7917 - val_loss: 274.0096 - val_mae: 274.0096
Epoch 10/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.4064 - mae: 173.4064 - val_loss: 291.3651 - val_mae: 291.3651
Epoch 11/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.5223 - mae: 173.5223 - val_loss: 231.1061 - val_mae: 231.1061
Epoch 12/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 188.1695 - mae: 188.1695 - val_loss: 234.4982 - val_mae: 234.4982
Epoch 13/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 178.7183 - mae: 178.7183 - val_loss: 241.3365 - val_mae: 241.3365
Epoch 14/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 187.1585 - mae: 187.1585 - val_loss: 289.4426 - val_mae: 289.4426
Epoch 15/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 185.1128 - mae: 185.1128 - val_loss: 224.6882 - val_mae: 224.6882
Epoch 16/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 176.3626 - mae: 176.3626 - val_loss: 236.0883 - val_mae: 236.0883
Epoch 17/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 169.4301 - mae: 169.4301 - val_loss: 253.5800 - val_mae: 253.5800
Epoch 18/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 182.8299 - mae: 182.8299 - val_loss: 230.9877 - val_mae: 230.9877
Epoch 19/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.4592 - mae: 163.4592 - val_loss: 275.7173 - val_mae: 275.7173
Epoch 20/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 164.3238 - mae: 164.3238 - val_loss: 213.8324 - val_mae: 213.8324
Epoch 21/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.1941 - mae: 173.1941 - val_loss: 288.5436 - val_mae: 288.5436
Epoch 22/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 182.3126 - mae: 182.3126 - val_loss: 252.1388 - val_mae: 252.1388
Epoch 23/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 179.3197 - mae: 179.3197 - val_loss: 258.5956 - val_mae: 258.5956
Epoch 24/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 182.5287 - mae: 182.5287 - val_loss: 459.1015 - val_mae: 459.1015
Epoch 25/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 195.3657 - mae: 195.3657 - val_loss: 227.6511 - val_mae: 227.6511
Epoch 26/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 181.6070 - mae: 181.6070 - val_loss: 233.4277 - val_mae: 233.4277
Epoch 27/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 170.7340 - mae: 170.7340 - val_loss: 236.9568 - val_mae: 236.9568
Epoch 28/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 192.4166 - mae: 192.4166 - val_loss: 235.0163 - val_mae: 235.0163
Epoch 29/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 179.5949 - mae: 179.5949 - val_loss: 212.6601 - val_mae: 212.6601
Epoch 30/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 180.8985 - mae: 180.8985 - val_loss: 277.2592 - val_mae: 277.2592
Epoch 31/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 180.7980 - mae: 180.7980 - val_loss: 240.1955 - val_mae: 240.1956
Epoch 32/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.9833 - mae: 158.9833 - val_loss: 357.3469 - val_mae: 357.3469
Epoch 33/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 184.2264 - mae: 184.2264 - val_loss: 326.6605 - val_mae: 326.6605
Epoch 34/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 171.2572 - mae: 171.2572 - val_loss: 226.5076 - val_mae: 226.5076
Epoch 35/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 206.8167 - mae: 206.8167 - val_loss: 252.2719 - val_mae: 252.2719
Epoch 36/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 195.2992 - mae: 195.2992 - val_loss: 214.1346 - val_mae: 214.1346
Epoch 37/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 179.5698 - mae: 179.5698 - val_loss: 233.7082 - val_mae: 233.7082
Epoch 38/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 185.4408 - mae: 185.4408 - val_loss: 238.2965 - val_mae: 238.2965
Epoch 39/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 183.5955 - mae: 183.5955 - val_loss: 281.4339 - val_mae: 281.4339
Epoch 40/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 188.2039 - mae: 188.2039 - val_loss: 224.0790 - val_mae: 224.0790
Epoch 41/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 168.7269 - mae: 168.7269 - val_loss: 240.3582 - val_mae: 240.3581
Epoch 42/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 183.0990 - mae: 183.0990 - val_loss: 313.8364 - val_mae: 313.8364
Epoch 43/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 188.9774 - mae: 188.9774 - val_loss: 231.7534 - val_mae: 231.7534
Epoch 44/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 190.8005 - mae: 190.8005 - val_loss: 315.3679 - val_mae: 315.3679
Epoch 45/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 177.0932 - mae: 177.0932 - val_loss: 298.4888 - val_mae: 298.4888
Epoch 46/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 183.7285 - mae: 183.7285 - val_loss: 205.4357 - val_mae: 205.4357
Epoch 47/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 197.6058 - mae: 197.6058 - val_loss: 216.5855 - val_mae: 216.5855
Epoch 48/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 167.4797 - mae: 167.4797 - val_loss: 201.5385 - val_mae: 201.5385
Epoch 49/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.1183 - mae: 159.1183 - val_loss: 208.5379 - val_mae: 208.5379
Epoch 50/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 182.3990 - mae: 182.3990 - val_loss: 238.6562 - val_mae: 238.6562
Epoch 51/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 166.4285 - mae: 166.4285 - val_loss: 251.6306 - val_mae: 251.6306
Epoch 52/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.7520 - mae: 163.7520 - val_loss: 236.9373 - val_mae: 236.9373
Epoch 53/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 179.7389 - mae: 179.7389 - val_loss: 364.8605 - val_mae: 364.8605
Epoch 54/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 144.3445 - mae: 144.3445 - val_loss: 230.6785 - val_mae: 230.6785
Epoch 55/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 182.0535 - mae: 182.0535 - val_loss: 234.5930 - val_mae: 234.5930
Epoch 56/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 178.5760 - mae: 178.5760 - val_loss: 214.5454 - val_mae: 214.5454
Epoch 57/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 193.5729 - mae: 193.5729 - val_loss: 232.2202 - val_mae: 232.2202
Epoch 58/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 166.6148 - mae: 166.6148 - val_loss: 231.7154 - val_mae: 231.7154
Epoch 59/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 175.7179 - mae: 175.7179 - val_loss: 236.3235 - val_mae: 236.3235
Epoch 60/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.0709 - mae: 163.0709 - val_loss: 300.3276 - val_mae: 300.3276
Epoch 61/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 157.5809 - mae: 157.5809 - val_loss: 396.8727 - val_mae: 396.8727
Epoch 62/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 168.2746 - mae: 168.2746 - val_loss: 292.5219 - val_mae: 292.5219
Epoch 63/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 153.1166 - mae: 153.1166 - val_loss: 221.9349 - val_mae: 221.9349
Epoch 64/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.7274 - mae: 158.7274 - val_loss: 235.5972 - val_mae: 235.5972
Epoch 65/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 184.5695 - mae: 184.5695 - val_loss: 269.8018 - val_mae: 269.8018
Epoch 66/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.0263 - mae: 173.0263 - val_loss: 220.4462 - val_mae: 220.4462
Epoch 67/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 182.4343 - mae: 182.4343 - val_loss: 265.9105 - val_mae: 265.9105
Epoch 68/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 192.4391 - mae: 192.4391 - val_loss: 216.3826 - val_mae: 216.3826
Epoch 69/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 187.2650 - mae: 187.2650 - val_loss: 221.4014 - val_mae: 221.4014
Epoch 70/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 166.4114 - mae: 166.4114 - val_loss: 272.3183 - val_mae: 272.3183
Epoch 71/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 187.5792 - mae: 187.5792 - val_loss: 230.9228 - val_mae: 230.9228
Epoch 72/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 193.0509 - mae: 193.0509 - val_loss: 212.8777 - val_mae: 212.8777
Epoch 73/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 193.2125 - mae: 193.2125 - val_loss: 243.3722 - val_mae: 243.3722
Epoch 74/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 144.7375 - mae: 144.7375 - val_loss: 258.5998 - val_mae: 258.5998
Epoch 75/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 165.3153 - mae: 165.3153 - val_loss: 302.9969 - val_mae: 302.9969
Epoch 76/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 164.9136 - mae: 164.9136 - val_loss: 241.4119 - val_mae: 241.4119
Epoch 77/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 161.1273 - mae: 161.1273 - val_loss: 325.4854 - val_mae: 325.4854
Epoch 78/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.3317 - mae: 158.3317 - val_loss: 228.1258 - val_mae: 228.1258
Epoch 79/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 172.2392 - mae: 172.2392 - val_loss: 267.2308 - val_mae: 267.2308
Epoch 80/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 165.0898 - mae: 165.0898 - val_loss: 284.6650 - val_mae: 284.6650
Epoch 81/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 183.7498 - mae: 183.7498 - val_loss: 321.7946 - val_mae: 321.7946
Epoch 82/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 189.7803 - mae: 189.7803 - val_loss: 258.8829 - val_mae: 258.8829
Epoch 83/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.8054 - mae: 154.8054 - val_loss: 238.8394 - val_mae: 238.8394
Epoch 84/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 156.3985 - mae: 156.3985 - val_loss: 274.6940 - val_mae: 274.6940
Epoch 85/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 151.2938 - mae: 151.2938 - val_loss: 252.6757 - val_mae: 252.6757
Epoch 86/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 171.3717 - mae: 171.3717 - val_loss: 247.2963 - val_mae: 247.2963
Epoch 87/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 157.4692 - mae: 157.4692 - val_loss: 236.7246 - val_mae: 236.7246
Epoch 88/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 168.1723 - mae: 168.1723 - val_loss: 227.8785 - val_mae: 227.8785
Epoch 89/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.2895 - mae: 154.2895 - val_loss: 250.7658 - val_mae: 250.7658
Epoch 90/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.1407 - mae: 163.1407 - val_loss: 224.0166 - val_mae: 224.0166
Epoch 91/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.2293 - mae: 154.2293 - val_loss: 264.5468 - val_mae: 264.5468
Epoch 92/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 166.7342 - mae: 166.7342 - val_loss: 232.2901 - val_mae: 232.2901
Epoch 93/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.3824 - mae: 159.3824 - val_loss: 241.6145 - val_mae: 241.6145
Epoch 94/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.5509 - mae: 159.5509 - val_loss: 311.0925 - val_mae: 311.0925
Epoch 95/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 168.4923 - mae: 168.4923 - val_loss: 264.3293 - val_mae: 264.3293
Epoch 96/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 192.0597 - mae: 192.0597 - val_loss: 283.2278 - val_mae: 283.2278
Epoch 97/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.3618 - mae: 154.3618 - val_loss: 285.5048 - val_mae: 285.5048
Epoch 98/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.3673 - mae: 154.3673 - val_loss: 220.7326 - val_mae: 220.7326
Epoch 99/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 160.4642 - mae: 160.4642 - val_loss: 245.3773 - val_mae: 245.3773
Epoch 100/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 150.5831 - mae: 150.5831 - val_loss: 275.1587 - val_mae: 275.1587
Epoch 101/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 171.3743 - mae: 171.3743 - val_loss: 225.3151 - val_mae: 225.3151
Epoch 102/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 161.0683 - mae: 161.0683 - val_loss: 257.4454 - val_mae: 257.4454
Epoch 103/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 149.4746 - mae: 149.4746 - val_loss: 236.9507 - val_mae: 236.9507
Epoch 104/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 160.3939 - mae: 160.3939 - val_loss: 221.3927 - val_mae: 221.3927
Epoch 105/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.7112 - mae: 159.7112 - val_loss: 221.4902 - val_mae: 221.4902
Epoch 106/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 143.5221 - mae: 143.5221 - val_loss: 225.9314 - val_mae: 225.9314
Epoch 107/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 157.9158 - mae: 157.9158 - val_loss: 213.8010 - val_mae: 213.8010
Epoch 108/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 147.3483 - mae: 147.3483 - val_loss: 217.3926 - val_mae: 217.3926
Epoch 109/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 150.9857 - mae: 150.9857 - val_loss: 206.4175 - val_mae: 206.4175
Epoch 110/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.8295 - mae: 158.8295 - val_loss: 223.9753 - val_mae: 223.9753
Epoch 111/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 147.7292 - mae: 147.7292 - val_loss: 250.9430 - val_mae: 250.9430
Epoch 112/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 153.7051 - mae: 153.7051 - val_loss: 346.1874 - val_mae: 346.1874
Epoch 113/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 152.5279 - mae: 152.5279 - val_loss: 272.0446 - val_mae: 272.0446
Epoch 114/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.0292 - mae: 154.0292 - val_loss: 208.5378 - val_mae: 208.5378
Epoch 115/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 160.2889 - mae: 160.2889 - val_loss: 227.9790 - val_mae: 227.9790
Epoch 116/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 175.7448 - mae: 175.7448 - val_loss: 229.7086 - val_mae: 229.7086
Epoch 117/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 156.0551 - mae: 156.0551 - val_loss: 256.0446 - val_mae: 256.0446
Epoch 118/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 169.5981 - mae: 169.5981 - val_loss: 268.5870 - val_mae: 268.5870
Epoch 119/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.2269 - mae: 159.2269 - val_loss: 233.2007 - val_mae: 233.2007
Epoch 120/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 162.3054 - mae: 162.3054 - val_loss: 216.3659 - val_mae: 216.3659
Epoch 121/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 155.3155 - mae: 155.3155 - val_loss: 208.0618 - val_mae: 208.0618
Epoch 122/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 150.7504 - mae: 150.7504 - val_loss: 304.1009 - val_mae: 304.1009
Epoch 123/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 175.3619 - mae: 175.3619 - val_loss: 271.3860 - val_mae: 271.3860
Epoch 124/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 157.2756 - mae: 157.2756 - val_loss: 222.6518 - val_mae: 222.6518
Epoch 125/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 141.7950 - mae: 141.7950 - val_loss: 222.5479 - val_mae: 222.5479
Epoch 126/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 157.3395 - mae: 157.3395 - val_loss: 250.3771 - val_mae: 250.3771
Epoch 127/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 146.4771 - mae: 146.4771 - val_loss: 271.4027 - val_mae: 271.4027
Epoch 128/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.4111 - mae: 158.4111 - val_loss: 281.5199 - val_mae: 281.5199
Epoch 129/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 157.6746 - mae: 157.6746 - val_loss: 224.3483 - val_mae: 224.3483
Epoch 130/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 156.4232 - mae: 156.4232 - val_loss: 220.3805 - val_mae: 220.3805
Epoch 131/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 150.0506 - mae: 150.0506 - val_loss: 210.4186 - val_mae: 210.4186
Epoch 132/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 147.9854 - mae: 147.9854 - val_loss: 211.8482 - val_mae: 211.8482
Epoch 133/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 146.9107 - mae: 146.9107 - val_loss: 210.9183 - val_mae: 210.9183
Epoch 134/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 140.0811 - mae: 140.0811 - val_loss: 295.7267 - val_mae: 295.7267
Epoch 135/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.4984 - mae: 163.4984 - val_loss: 385.6700 - val_mae: 385.6700
Epoch 136/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 171.5394 - mae: 171.5394 - val_loss: 225.1656 - val_mae: 225.1656
Epoch 137/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.8737 - mae: 158.8737 - val_loss: 239.8893 - val_mae: 239.8893
Epoch 138/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 148.2600 - mae: 148.2600 - val_loss: 205.8112 - val_mae: 205.8112
Epoch 139/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 147.7309 - mae: 147.7309 - val_loss: 225.9099 - val_mae: 225.9099
Epoch 140/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 151.0527 - mae: 151.0527 - val_loss: 229.0816 - val_mae: 229.0816
Epoch 141/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 147.0349 - mae: 147.0349 - val_loss: 242.3187 - val_mae: 242.3187
Epoch 142/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 141.0805 - mae: 141.0805 - val_loss: 254.7449 - val_mae: 254.7449
Epoch 143/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 153.1526 - mae: 153.1526 - val_loss: 279.8200 - val_mae: 279.8200
Epoch 144/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 157.6776 - mae: 157.6776 - val_loss: 225.6281 - val_mae: 225.6281
Epoch 145/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 153.5799 - mae: 153.5799 - val_loss: 231.9510 - val_mae: 231.9510
Epoch 146/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 143.6638 - mae: 143.6638 - val_loss: 239.9107 - val_mae: 239.9107
Epoch 147/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.5034 - mae: 158.5034 - val_loss: 206.9690 - val_mae: 206.9690
Epoch 148/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 148.9432 - mae: 148.9432 - val_loss: 263.8371 - val_mae: 263.8371
Epoch 149/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 141.8139 - mae: 141.8139 - val_loss: 221.3156 - val_mae: 221.3156
Epoch 150/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 134.0045 - mae: 134.0045 - val_loss: 223.0622 - val_mae: 223.0622
Epoch 151/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 141.3436 - mae: 141.3436 - val_loss: 256.4534 - val_mae: 256.4534
Epoch 152/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 143.8874 - mae: 143.8874 - val_loss: 265.5747 - val_mae: 265.5747
Epoch 153/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 153.5473 - mae: 153.5473 - val_loss: 222.5611 - val_mae: 222.5611
Epoch 154/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 141.5546 - mae: 141.5546 - val_loss: 222.2944 - val_mae: 222.2944
Epoch 155/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 131.1278 - mae: 131.1278 - val_loss: 220.5072 - val_mae: 220.5072
Epoch 156/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 144.8887 - mae: 144.8887 - val_loss: 208.9149 - val_mae: 208.9149
Epoch 157/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 146.3866 - mae: 146.3866 - val_loss: 307.0637 - val_mae: 307.0637
Epoch 158/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 153.5852 - mae: 153.5852 - val_loss: 269.1821 - val_mae: 269.1821
Epoch 159/300

In [2626]:
X_new = X_test[:3] 
y_pred = model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

In [2627]:
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

0.8182715813953968

In [2629]:
model.save("price_predictor.keras")