In [50]:
import pandas as pd
obesidad = pd.read_csv("Obesidad.csv")
print(obesidad.columns)

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Gender', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

In [51]:
obesidad_recortado = obesidad[['YearStart','LocationAbbr','Topic','Question','Data_Value','Stratification1','StratificationCategory1']]

In [52]:
obesidad_recortado['Topic'].unique()

array(['Obesity / Weight Status', 'Fruits and Vegetables - Behavior',
       'Physical Activity - Behavior'], dtype=object)

In [53]:
# Definimos el mapa de nombres cortos
question_map = {
    'Percent of adults aged 18 years and older who have obesity': 'obesidad_pct',
    'Percent of adults aged 18 years and older who have an overweight classification': 'sobrepeso_pct',
    'Percent of adults who report consuming fruit less than one time daily': 'fruta_baja_pct',
    'Percent of adults who report consuming vegetables less than one time daily': 'verduras_baja_pct',
    'Percent of adults who engage in no leisure-time physical activity': 'sin_ejercicio_pct',
    'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity': 'ejercicio_aerobico_pct',
    'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)': 'ejercicio_150min_pct',
    'Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic physical activity and engage in muscle-strengthening activities on 2 or more days a week': 'ejercicio_y_fuerza_pct',
    'Percent of adults who achieve at least 300 minutes a week of moderate-intensity aerobic physical activity or 150 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)': 'ejercicio_300min_pct',
    'Percent of adults who engage in muscle-strengthening activities on 2 or more days a week': 'fuerza_muscular_pct'
}
obesidad_recortado['Question'] = obesidad_recortado['Question'].replace(question_map)
obesidad_recortado.dropna(subset=['Data_Value'], inplace=True)

/tmp/ipykernel_12076/590949371.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  obesidad_recortado['Question'] = obesidad_recortado['Question'].replace(question_map)
/tmp/ipykernel_12076/590949371.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  obesidad_recortado.dropna(subset=['Data_Value'], inplace=True)

In [54]:
obesidad_recortado.head(20)

,YearStart,LocationAbbr,Topic,Question,Data_Value,Stratification1,StratificationCategory1
0,2011,AL,Obesity / Weight Status,obesidad_pct,32.0,Total,Total
1,2011,AL,Obesity / Weight Status,obesidad_pct,32.3,Male,Gender
2,2011,AL,Obesity / Weight Status,obesidad_pct,31.8,Female,Gender
3,2011,AL,Obesity / Weight Status,obesidad_pct,33.6,Less than high school,Education
4,2011,AL,Obesity / Weight Status,obesidad_pct,32.8,High school graduate,Education
5,2011,AL,Obesity / Weight Status,obesidad_pct,33.8,Some college or technical school,Education
6,2011,AL,Obesity / Weight Status,obesidad_pct,26.4,College graduate,Education
7,2011,AL,Obesity / Weight Status,obesidad_pct,16.3,18 - 24,Age (years)
8,2011,AL,Obesity / Weight Status,obesidad_pct,35.2,25 - 34,Age (years)
9,2011,AL,Obesity / Weight Status,obesidad_pct,35.5,35 - 44,Age (years)
10,2011,AL,Obesity / Weight Status,obesidad_pct,38.0,45 - 54,Age (years)
11,2011,AL,Obesity / Weight Status,obesidad_pct,36.4,55 - 64,Age (years)
12,2011,AL,Obesity / Weight Status,obesidad_pct,27.1,65 or older,Age (years)
13,2011,AL,Obesity / Weight Status,obesidad_pct,38.5,"Less than $15,000",Income
14,2011,AL,Obesity / Weight Status,obesidad_pct,34.8,"$15,000 - $24,999",Income
15,2011,AL,Obesity / Weight Status,obesidad_pct,35.8,"$25,000 - $34,999",Income
16,2011,AL,Obesity / Weight Status,obesidad_pct,32.3,"$35,000 - $49,999",Income
17,2011,AL,Obesity / Weight Status,obesidad_pct,34.1,"$50,000 - $74,999",Income
18,2011,AL,Obesity / Weight Status,obesidad_pct,28.8,"$75,000 or greater",Income
19,2011,AL,Obesity / Weight Status,obesidad_pct,23.8,Data not reported,Income

In [55]:
df_pivot = obesidad_recortado.pivot_table(
    index=['YearStart', 'LocationAbbr', 'Stratification1'],
    columns='Question',
    values='Data_Value'
).reset_index()

df_pivot.columns.name = None

In [56]:
df_pivot.head(20)

,YearStart,LocationAbbr,Stratification1,ejercicio_150min_pct,ejercicio_300min_pct,ejercicio_y_fuerza_pct,fruta_baja_pct,fuerza_muscular_pct,obesidad_pct,sin_ejercicio_pct,sobrepeso_pct,verduras_baja_pct
0,2011,AK,"$15,000 - $24,999",51.8,32.7,17.3,44.6,28.1,30.2,24.6,33.5,26.1
1,2011,AK,"$25,000 - $34,999",57.9,38.2,20.2,45.6,24.5,32.2,25.8,38.1,24.4
2,2011,AK,"$35,000 - $49,999",55.1,34.1,21.6,37.2,31.4,24.5,25.7,42.3,19.4
3,2011,AK,"$50,000 - $74,999",59.3,32.6,26.1,39.1,37.7,27.8,19.2,41.6,16.5
4,2011,AK,"$75,000 or greater",63.2,44.8,30.8,31.9,38.0,26.9,17.1,39.9,11.8
5,2011,AK,18 - 24,62.8,32.4,34.9,45.0,51.9,19.8,16.1,32.0,29.1
6,2011,AK,2 or more races,56.2,33.3,25.1,29.2,26.9,23.3,30.2,41.9,17.9
7,2011,AK,25 - 34,57.6,35.7,27.0,43.6,36.4,23.5,18.1,38.7,18.8
8,2011,AK,35 - 44,55.3,32.3,22.2,42.3,30.8,29.5,21.1,38.9,18.4
9,2011,AK,45 - 54,56.2,38.8,25.2,35.8,32.4,29.2,24.7,43.3,17.0
10,2011,AK,55 - 64,58.2,43.3,20.1,33.3,26.6,33.4,26.0,38.9,16.0
11,2011,AK,65 or older,58.9,46.6,19.8,28.8,24.2,29.3,27.4,40.9,22.0
12,2011,AK,American Indian/Alaska Native,52.2,33.8,17.4,47.7,23.3,30.9,31.7,37.2,36.7
13,2011,AK,College graduate,67.2,43.3,33.8,28.9,41.8,22.1,12.5,39.9,12.8
14,2011,AK,Data not reported,52.7,33.6,23.1,43.6,32.7,22.7,27.2,43.7,27.0
15,2011,AK,Female,57.4,37.5,21.7,34.2,28.9,26.7,24.0,31.3,16.2
16,2011,AK,High school graduate,49.9,30.1,17.4,47.5,25.9,33.1,26.9,38.0,25.4
17,2011,AK,Hispanic,46.5,34.0,15.7,51.7,30.9,31.5,23.5,37.4,27.5
18,2011,AK,"Less than $15,000",56.0,38.1,22.3,46.5,30.3,33.6,25.0,24.6,35.0
19,2011,AK,Less than high school,53.1,39.5,20.7,43.3,28.8,28.8,33.2,35.3,27.5

In [58]:
df_pivot.corr(numeric_only=True)['obesidad_pct'].sort_values(ascending=False)[1:]

sin_ejercicio_pct         0.486281
fruta_baja_pct            0.394288
verduras_baja_pct         0.362508
YearStart                 0.118849
sobrepeso_pct             0.035635
ejercicio_300min_pct     -0.307280
ejercicio_150min_pct     -0.450314
fuerza_muscular_pct      -0.483511
ejercicio_y_fuerza_pct   -0.485847
Name: obesidad_pct, dtype: float64