In [2]:
import pandas as pd
obesidad = pd.read_csv("Obesidad.csv")
print(obesidad.columns)

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Gender', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

In [3]:
obesidad_recortado = obesidad[['YearStart','LocationAbbr','Topic','Question','Data_Value','Stratification1','StratificationCategory1']]

In [9]:
obesidad_recortado['Topic'].unique()

array(['Obesity / Weight Status', 'Fruits and Vegetables - Behavior',
       'Physical Activity - Behavior'], dtype=object)

In [8]:
obesidad_recortado.head(20)

,YearStart,LocationAbbr,Topic,Question,Data_Value,Stratification1,StratificationCategory1
0,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.0,Total,Total
1,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.3,Male,Gender
2,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,31.8,Female,Gender
3,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,33.6,Less than high school,Education
4,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.8,High school graduate,Education
5,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,33.8,Some college or technical school,Education
6,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,26.4,College graduate,Education
7,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,16.3,18 - 24,Age (years)
8,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,35.2,25 - 34,Age (years)
9,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,35.5,35 - 44,Age (years)
10,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,38.0,45 - 54,Age (years)
11,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,36.4,55 - 64,Age (years)
12,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,27.1,65 or older,Age (years)
13,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,38.5,"Less than $15,000",Income
14,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,34.8,"$15,000 - $24,999",Income
15,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,35.8,"$25,000 - $34,999",Income
16,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.3,"$35,000 - $49,999",Income
17,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,34.1,"$50,000 - $74,999",Income
18,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,28.8,"$75,000 or greater",Income
19,2011,AL,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,23.8,Data not reported,Income

In [ ]:
# 3. Transformar de formato largo a formato ancho
df_pivot = obesidad_recortado.pivot_table(
    index=['YearStart', 'LocationAbbr', 'StratificationCategory1', 'Stratification1'],
    columns='Question',
    values='Data_Value'
).reset_index()

df_pivot.columns.name = None  # Elimina el nombre de la jerarquía de columnas

In [12]:
df_pivot.head(20)

,YearStart,LocationAbbr,StratificationCategory1,Stratification1,Percent of adults aged 18 years and older who have an overweight classification,Percent of adults aged 18 years and older who have obesity,Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination),Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic physical activity and engage in muscle-strengthening activities on 2 or more days a week,Percent of adults who achieve at least 300 minutes a week of moderate-intensity aerobic physical activity or 150 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination),Percent of adults who engage in muscle-strengthening activities on 2 or more days a week,Percent of adults who engage in no leisure-time physical activity,Percent of adults who report consuming fruit less than one time daily,Percent of adults who report consuming vegetables less than one time daily
0,2011,AK,Age (years),18 - 24,32.0,19.8,62.8,34.9,32.4,51.9,16.1,45.0,29.1
1,2011,AK,Age (years),25 - 34,38.7,23.5,57.6,27.0,35.7,36.4,18.1,43.6,18.8
2,2011,AK,Age (years),35 - 44,38.9,29.5,55.3,22.2,32.3,30.8,21.1,42.3,18.4
3,2011,AK,Age (years),45 - 54,43.3,29.2,56.2,25.2,38.8,32.4,24.7,35.8,17.0
4,2011,AK,Age (years),55 - 64,38.9,33.4,58.2,20.1,43.3,26.6,26.0,33.3,16.0
5,2011,AK,Age (years),65 or older,40.9,29.3,58.9,19.8,46.6,24.2,27.4,28.8,22.0
6,2011,AK,Education,College graduate,39.9,22.1,67.2,33.8,43.3,41.8,12.5,28.9,12.8
7,2011,AK,Education,High school graduate,38.0,33.1,49.9,17.4,30.1,25.9,26.9,47.5,25.4
8,2011,AK,Education,Less than high school,35.3,28.8,53.1,20.7,39.5,28.8,33.2,43.3,27.5
9,2011,AK,Education,Some college or technical school,40.1,25.8,59.3,26.0,39.3,36.0,21.2,37.3,17.7
10,2011,AK,Gender,Female,31.3,26.7,57.4,21.7,37.5,28.9,24.0,34.2,16.2
11,2011,AK,Gender,Male,45.3,28.0,58.4,28.1,37.8,38.6,20.1,42.9,23.0
12,2011,AK,Income,"$15,000 - $24,999",33.5,30.2,51.8,17.3,32.7,28.1,24.6,44.6,26.1
13,2011,AK,Income,"$25,000 - $34,999",38.1,32.2,57.9,20.2,38.2,24.5,25.8,45.6,24.4
14,2011,AK,Income,"$35,000 - $49,999",42.3,24.5,55.1,21.6,34.1,31.4,25.7,37.2,19.4
15,2011,AK,Income,"$50,000 - $74,999",41.6,27.8,59.3,26.1,32.6,37.7,19.2,39.1,16.5
16,2011,AK,Income,"$75,000 or greater",39.9,26.9,63.2,30.8,44.8,38.0,17.1,31.9,11.8
17,2011,AK,Income,Data not reported,43.7,22.7,52.7,23.1,33.6,32.7,27.2,43.6,27.0
18,2011,AK,Income,"Less than $15,000",24.6,33.6,56.0,22.3,38.1,30.3,25.0,46.5,35.0
19,2011,AK,Race/Ethnicity,2 or more races,41.9,23.3,56.2,25.1,33.3,26.9,30.2,29.2,17.9