In [3]:
from os import listdir
from numpy import asarray
from numpy import save
import tensorflow as tf
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from tensorflow import keras
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVR
from sklearn.metrics import classification_report
import datetime
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from sklearn.decomposition import PCA

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778522752.378998   84050 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1778522752.420312   84050 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778522755.183186   84050 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

Rúbrica: 

A continuación se muestra la rúbrica con la que se va a corregir el examen:


| Apartado/Criterio | Ponderación | 
| :-- | --- | 
| Ej. 1. Ha tratado de manera adecuada los datos de las columnas. | 0,5 | 
| Ej. 1. Ha usado como entrada las columnas adecuadas. | 0,5 |
| Ej. 1. Ha diseñado bien la red, el sistema de entrenamiento y ha comprobado si el resultado es bueno | 0,5 | 
| Ej. 1. Ha dimensionado bien la red neuronal. | 0,5 | 
| Ej. 1. Ha usado adecuadamente las técnicas de deep learning. | 2 | 
| Ej. 1. Ha tratado de realizar una predicción de forma adecuada. | 1,5 | 
| Ej. 2. Ha cargado los datos probando los dos métodos propuestos. | 1,5 | 
| Ej. 2. Ha diseñado bien la red convolucional y el sistema de entrenamiento | 1,5 | 
| Ej. 2. Ha dimensionado bien la red neuronal. | 0,5 | 
| Ej. 2. Ha usado las técnicas y el proceso visto en clase. | 0,5 | 
| Ej. 2. Ha usado su experiencia para valorar si el resultado es válido o no. | 0,5 |

# EJERCICIO 1

In [86]:
df_destruction = pd.read_csv("destruccion_empleo.csv")
df_destruction.head()

,record_id,country,iso3_code,region,income_group,year,quarter,quarter_label,industry_sector,sector_automation_risk_score,gdp_per_capita_usd,pct_sector_workforce_displaced,data_source_notes
0,1,United States,USA,North America,High Income,2020,1,2020-Q1,Technology & Software,0.382,63514,0.0406,Research-calibrated synthetic data. Grounded i...
1,2,United States,USA,North America,High Income,2020,1,2020-Q1,Finance & Banking,0.608,63514,0.0517,Research-calibrated synthetic data. Grounded i...
2,3,United States,USA,North America,High Income,2020,1,2020-Q1,Healthcare & Life Sciences,0.198,63514,0.0176,Research-calibrated synthetic data. Grounded i...
3,4,United States,USA,North America,High Income,2020,1,2020-Q1,Manufacturing & Industry,0.720,63514,0.0924,Research-calibrated synthetic data. Grounded i...
4,5,United States,USA,North America,High Income,2020,1,2020-Q1,Retail & E-Commerce,0.676,63514,0.0667,Research-calibrated synthetic data. Grounded i...

In [87]:
df_destruction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   record_id                       20800 non-null  int64
 1   country                         20800 non-null  object
 2   iso3_code                       20800 non-null  object
 3   region                          20800 non-null  object
 4   income_group                    20800 non-null  object
 5   year                            20800 non-null  int64
 6   quarter                         20800 non-null  int64
 7   quarter_label                   20800 non-null  object
 8   industry_sector                 20800 non-null  object
 9   sector_automation_risk_score    20800 non-null  float64
 10  gdp_per_capita_usd              20800 non-null  int64
 11  pct_sector_workforce_displaced  20800 non-null  float64
 12  data_source_notes               20800 non-null  object
dtypes: float64(2), int64(4), object(7)
memory usage: 2.1+ MB

In [88]:
df_destruction["industry_sector"].unique()

array(['Technology & Software', 'Finance & Banking',
       'Healthcare & Life Sciences', 'Manufacturing & Industry',
       'Retail & E-Commerce', 'Education & Research',
       'Transportation & Logistics', 'Media & Communications',
       'Administrative & Clerical', 'Energy & Utilities'], dtype=object)

In [89]:
#Borro quarter label porque teniendo ya el año y el cuatrimestre es tonteria tenerla, el iso3_code porque teniendo ya el pais también es innecesario ya que es lo mismo
#data_source_notes lo borro porque solo tiene un valor, se podría quitar region por lo mismo, tenemos los paises entonces se puede presuponer la region,
#pero la voy a dejar porque no estoy 100% seguro, record_id se borra porque es variable con valores diferentes todo el rato 
df_destruction.drop(columns=["quarter_label", "iso3_code","data_source_notes", "record_id"], inplace=True)

In [90]:
#No hay nulos asi que esa parte de limpieza nos la quitamos, por lo que realizo un dummies para la limpieza de variables object
df_destruction = pd.get_dummies(df_destruction,dtype=int)

In [91]:
print(df_destruction.shape)
df_destruction.head()

(20800, 111)

,year,quarter,sector_automation_risk_score,gdp_per_capita_usd,pct_sector_workforce_displaced,country_Algeria,country_Argentina,country_Australia,country_Austria,country_Bangladesh,...,industry_sector_Administrative & Clerical,industry_sector_Education & Research,industry_sector_Energy & Utilities,industry_sector_Finance & Banking,industry_sector_Healthcare & Life Sciences,industry_sector_Manufacturing & Industry,industry_sector_Media & Communications,industry_sector_Retail & E-Commerce,industry_sector_Technology & Software,industry_sector_Transportation & Logistics
0,2020,1,0.382,63514,0.0406,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,2020,1,0.608,63514,0.0517,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,2020,1,0.198,63514,0.0176,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,2020,1,0.720,63514,0.0924,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,2020,1,0.676,63514,0.0667,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [92]:
X = df_destruction[0:5000].drop(columns=["pct_sector_workforce_displaced"])
y = df_destruction["pct_sector_workforce_displaced"][0:5000]

In [93]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [94]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [95]:
#Tiro ramdon forest regressor por si acaso
rf = RandomForestRegressor(n_estimators=700, n_jobs=-1)
rf.fit(X_train,y_train)
print("R² score", rf.score(X_test,y_test))

R² score 0.9465143908430713

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(512,input_shape=X_train.shape[1:], activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(256,activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1, kernel_initializer='glorot_normal'))

/home/ciabd12/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [110]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(2048,input_shape=X_train.shape[1:], activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(512,activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1, kernel_initializer='glorot_normal'))

/home/ciabd12/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [103]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(3000,input_shape=X_train.shape[1:], activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(800,activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1, kernel_initializer='glorot_normal'))

/home/ciabd12/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [111]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(2000,input_shape=X_train.shape[1:], activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(500,activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1, kernel_initializer='glorot_normal'))

In [114]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(2048,input_shape=X_train.shape[1:], activation='relu', kernel_initializer='he_normal'))
# model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(512,activation='relu', kernel_initializer='he_normal'))
# model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(1, kernel_initializer='glorot_normal'))

/home/ciabd12/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [115]:
#He tenido que reducir la cantidad de fotos porque me tarda 40 segundos por epoca
early_stopping_cb = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
model.compile(loss='mean_absolute_error', metrics=['mae'],optimizer = keras.optimizers.Adam(learning_rate=0.0001,beta_1=0.9,beta_2=0.999))
history = model.fit(X_train, y_train, epochs=100000, validation_split = 0.1, callbacks=[early_stopping_cb])

Epoch 1/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.2113 - mae: 0.2113 - val_loss: 0.1472 - val_mae: 0.1472
Epoch 2/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1394 - mae: 0.1394 - val_loss: 0.1315 - val_mae: 0.1315
Epoch 3/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1308 - mae: 0.1308 - val_loss: 0.1058 - val_mae: 0.1058
Epoch 4/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1079 - mae: 0.1079 - val_loss: 0.1016 - val_mae: 0.1016
Epoch 5/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.1022 - mae: 0.1022 - val_loss: 0.0935 - val_mae: 0.0935
Epoch 6/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0968 - mae: 0.0968 - val_loss: 0.1107 - val_mae: 0.1107
Epoch 7/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0865 - mae: 0.0865 - val_loss: 0.1017 - val_mae: 0.1017
Epoch 8/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0857 - mae: 0.0857 - val_loss: 0.0778 - val_mae: 0.0778
Epoch 9/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0816 - mae: 0.0816 - val_loss: 0.0665 - val_mae: 0.0665
Epoch 10/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0696 - mae: 0.0696 - val_loss: 0.0580 - val_mae: 0.0580
Epoch 11/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0738 - mae: 0.0738 - val_loss: 0.0650 - val_mae: 0.0650
Epoch 12/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0670 - mae: 0.0670 - val_loss: 0.0879 - val_mae: 0.0879
Epoch 13/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0664 - mae: 0.0664 - val_loss: 0.0668 - val_mae: 0.0668
Epoch 14/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0572 - mae: 0.0572 - val_loss: 0.0731 - val_mae: 0.0731
Epoch 15/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0606 - mae: 0.0606 - val_loss: 0.0771 - val_mae: 0.0771
Epoch 16/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0583 - mae: 0.0583 - val_loss: 0.0519 - val_mae: 0.0519
Epoch 17/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0491 - mae: 0.0491 - val_loss: 0.0467 - val_mae: 0.0467
Epoch 18/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0489 - mae: 0.0489 - val_loss: 0.0420 - val_mae: 0.0420
Epoch 19/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0442 - mae: 0.0442 - val_loss: 0.0397 - val_mae: 0.0397
Epoch 20/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0408 - mae: 0.0408 - val_loss: 0.0464 - val_mae: 0.0464
Epoch 21/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0472 - mae: 0.0472 - val_loss: 0.0475 - val_mae: 0.0475
Epoch 22/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0411 - mae: 0.0411 - val_loss: 0.0375 - val_mae: 0.0375
Epoch 23/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0363 - mae: 0.0363 - val_loss: 0.0352 - val_mae: 0.0352
Epoch 24/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0339 - mae: 0.0339 - val_loss: 0.0384 - val_mae: 0.0384
Epoch 25/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0366 - mae: 0.0366 - val_loss: 0.0406 - val_mae: 0.0406
Epoch 26/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0327 - mae: 0.0327 - val_loss: 0.0302 - val_mae: 0.0302
Epoch 27/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0323 - mae: 0.0323 - val_loss: 0.0371 - val_mae: 0.0371
Epoch 28/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0312 - mae: 0.0312 - val_loss: 0.0340 - val_mae: 0.0340
Epoch 29/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0308 - mae: 0.0308 - val_loss: 0.0332 - val_mae: 0.0332
Epoch 30/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0282 - mae: 0.0282 - val_loss: 0.0373 - val_mae: 0.0373
Epoch 31/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0281 - mae: 0.0281 - val_loss: 0.0310 - val_mae: 0.0310
Epoch 32/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0287 - mae: 0.0287 - val_loss: 0.0287 - val_mae: 0.0287
Epoch 33/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0261 - mae: 0.0261 - val_loss: 0.0302 - val_mae: 0.0302
Epoch 34/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0269 - mae: 0.0269 - val_loss: 0.0279 - val_mae: 0.0279
Epoch 35/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0256 - mae: 0.0256 - val_loss: 0.0270 - val_mae: 0.0270
Epoch 36/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0261 - mae: 0.0261 - val_loss: 0.0269 - val_mae: 0.0269
Epoch 37/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0238 - mae: 0.0238 - val_loss: 0.0252 - val_mae: 0.0252
Epoch 38/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0246 - mae: 0.0246 - val_loss: 0.0290 - val_mae: 0.0290
Epoch 39/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0248 - mae: 0.0248 - val_loss: 0.0319 - val_mae: 0.0319
Epoch 40/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0223 - mae: 0.0223 - val_loss: 0.0219 - val_mae: 0.0219
Epoch 41/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0213 - mae: 0.0213 - val_loss: 0.0239 - val_mae: 0.0239
Epoch 42/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0211 - mae: 0.0211 - val_loss: 0.0212 - val_mae: 0.0212
Epoch 43/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0209 - mae: 0.0209 - val_loss: 0.0209 - val_mae: 0.0209
Epoch 44/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0202 - mae: 0.0202 - val_loss: 0.0209 - val_mae: 0.0209
Epoch 45/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0210 - mae: 0.0210 - val_loss: 0.0251 - val_mae: 0.0251
Epoch 46/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0210 - mae: 0.0210 - val_loss: 0.0212 - val_mae: 0.0212
Epoch 47/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0186 - mae: 0.0186 - val_loss: 0.0175 - val_mae: 0.0175
Epoch 48/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0185 - mae: 0.0185 - val_loss: 0.0194 - val_mae: 0.0194
Epoch 49/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0178 - mae: 0.0178 - val_loss: 0.0176 - val_mae: 0.0176
Epoch 50/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0177 - mae: 0.0177 - val_loss: 0.0200 - val_mae: 0.0200
Epoch 51/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0188 - mae: 0.0188 - val_loss: 0.0187 - val_mae: 0.0187
Epoch 52/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0165 - mae: 0.0165 - val_loss: 0.0172 - val_mae: 0.0172
Epoch 53/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0170 - mae: 0.0170 - val_loss: 0.0165 - val_mae: 0.0165
Epoch 54/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0153 - mae: 0.0153 - val_loss: 0.0188 - val_mae: 0.0188
Epoch 55/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0154 - mae: 0.0154 - val_loss: 0.0176 - val_mae: 0.0176
Epoch 56/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0148 - mae: 0.0148 - val_loss: 0.0173 - val_mae: 0.0173
Epoch 57/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0163 - mae: 0.0163 - val_loss: 0.0202 - val_mae: 0.0202
Epoch 58/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0153 - mae: 0.0153 - val_loss: 0.0171 - val_mae: 0.0171
Epoch 59/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0148 - mae: 0.0148 - val_loss: 0.0182 - val_mae: 0.0182
Epoch 60/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0143 - mae: 0.0143 - val_loss: 0.0143 - val_mae: 0.0143
Epoch 61/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0147 - mae: 0.0147 - val_loss: 0.0149 - val_mae: 0.0149
Epoch 62/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0140 - mae: 0.0140 - val_loss: 0.0153 - val_mae: 0.0153
Epoch 63/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0140 - mae: 0.0140 - val_loss: 0.0189 - val_mae: 0.0189
Epoch 64/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0135 - mae: 0.0135 - val_loss: 0.0179 - val_mae: 0.0179
Epoch 65/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0147 - mae: 0.0147 - val_loss: 0.0141 - val_mae: 0.0141
Epoch 66/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0134 - mae: 0.0134 - val_loss: 0.0148 - val_mae: 0.0148
Epoch 67/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0136 - mae: 0.0136 - val_loss: 0.0147 - val_mae: 0.0147
Epoch 68/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0125 - mae: 0.0125 - val_loss: 0.0154 - val_mae: 0.0154
Epoch 69/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0125 - mae: 0.0125 - val_loss: 0.0146 - val_mae: 0.0146
Epoch 70/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0129 - mae: 0.0129 - val_loss: 0.0145 - val_mae: 0.0145
Epoch 71/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0123 - mae: 0.0123 - val_loss: 0.0138 - val_mae: 0.0138
Epoch 72/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0124 - mae: 0.0124 - val_loss: 0.0141 - val_mae: 0.0141
Epoch 73/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0121 - mae: 0.0121 - val_loss: 0.0149 - val_mae: 0.0149
Epoch 74/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0122 - mae: 0.0122 - val_loss: 0.0153 - val_mae: 0.0153
Epoch 75/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0122 - mae: 0.0122 - val_loss: 0.0153 - val_mae: 0.0153
Epoch 76/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0128 - mae: 0.0128 - val_loss: 0.0169 - val_mae: 0.0169
Epoch 77/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0147 - val_mae: 0.0147
Epoch 78/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0114 - mae: 0.0114 - val_loss: 0.0160 - val_mae: 0.0160
Epoch 79/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0120 - mae: 0.0120 - val_loss: 0.0155 - val_mae: 0.0155
Epoch 80/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0108 - mae: 0.0108 - val_loss: 0.0138 - val_mae: 0.0138
Epoch 81/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0111 - mae: 0.0111 - val_loss: 0.0128 - val_mae: 0.0128
Epoch 82/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0106 - mae: 0.0106 - val_loss: 0.0140 - val_mae: 0.0140
Epoch 83/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0113 - mae: 0.0113 - val_loss: 0.0141 - val_mae: 0.0141
Epoch 84/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0112 - mae: 0.0112 - val_loss: 0.0130 - val_mae: 0.0130
Epoch 85/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0104 - mae: 0.0104 - val_loss: 0.0118 - val_mae: 0.0118
Epoch 86/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0115 - mae: 0.0115 - val_loss: 0.0135 - val_mae: 0.0135
Epoch 87/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0104 - mae: 0.0104 - val_loss: 0.0153 - val_mae: 0.0153
Epoch 88/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0108 - mae: 0.0108 - val_loss: 0.0125 - val_mae: 0.0125
Epoch 89/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0109 - mae: 0.0109 - val_loss: 0.0132 - val_mae: 0.0132
Epoch 90/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0102 - mae: 0.0102 - val_loss: 0.0123 - val_mae: 0.0123
Epoch 91/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0107 - mae: 0.0107 - val_loss: 0.0118 - val_mae: 0.0118
Epoch 92/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0107 - mae: 0.0107 - val_loss: 0.0130 - val_mae: 0.0130
Epoch 93/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0096 - mae: 0.0096 - val_loss: 0.0132 - val_mae: 0.0132
Epoch 94/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0109 - mae: 0.0109 - val_loss: 0.0130 - val_mae: 0.0130
Epoch 95/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0103 - mae: 0.0103 - val_loss: 0.0121 - val_mae: 0.0121
Epoch 96/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0095 - mae: 0.0095 - val_loss: 0.0117 - val_mae: 0.0117
Epoch 97/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0099 - mae: 0.0099 - val_loss: 0.0124 - val_mae: 0.0124
Epoch 98/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0093 - mae: 0.0093 - val_loss: 0.0120 - val_mae: 0.0120
Epoch 99/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0100 - mae: 0.0100 - val_loss: 0.0131 - val_mae: 0.0131
Epoch 100/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0092 - mae: 0.0092 - val_loss: 0.0118 - val_mae: 0.0118
Epoch 101/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0096 - mae: 0.0096 - val_loss: 0.0111 - val_mae: 0.0111
Epoch 102/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0094 - mae: 0.0094 - val_loss: 0.0115 - val_mae: 0.0115
Epoch 103/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0096 - mae: 0.0096 - val_loss: 0.0122 - val_mae: 0.0122
Epoch 104/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0093 - mae: 0.0093 - val_loss: 0.0113 - val_mae: 0.0113
Epoch 105/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0092 - mae: 0.0092 - val_loss: 0.0115 - val_mae: 0.0115
Epoch 106/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0090 - mae: 0.0090 - val_loss: 0.0122 - val_mae: 0.0122
Epoch 107/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0086 - mae: 0.0086 - val_loss: 0.0107 - val_mae: 0.0107
Epoch 108/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0089 - mae: 0.0089 - val_loss: 0.0109 - val_mae: 0.0109
Epoch 109/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0087 - mae: 0.0087 - val_loss: 0.0109 - val_mae: 0.0109
Epoch 110/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0086 - mae: 0.0086 - val_loss: 0.0112 - val_mae: 0.0112
Epoch 111/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0085 - mae: 0.0085 - val_loss: 0.0112 - val_mae: 0.0112
Epoch 112/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0085 - mae: 0.0085 - val_loss: 0.0136 - val_mae: 0.0136
Epoch 113/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0088 - mae: 0.0088 - val_loss: 0.0115 - val_mae: 0.0115
Epoch 114/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0088 - mae: 0.0088 - val_loss: 0.0112 - val_mae: 0.0112
Epoch 115/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0083 - mae: 0.0083 - val_loss: 0.0112 - val_mae: 0.0112
Epoch 116/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0083 - mae: 0.0083 - val_loss: 0.0118 - val_mae: 0.0118
Epoch 117/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0084 - mae: 0.0084 - val_loss: 0.0127 - val_mae: 0.0127

In [108]:
early_stopping_cb = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
model.compile(loss='mean_absolute_error', metrics=['mae'],optimizer = keras.optimizers.RMSprop(learning_rate=0.0001,rho=0.9))
history = model.fit(X_train, y_train, epochs=100000 , validation_split = 0.1, callbacks=[early_stopping_cb])

Epoch 1/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.5652 - mae: 0.5652 - val_loss: 0.4449 - val_mae: 0.4449
Epoch 2/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.4764 - mae: 0.4764 - val_loss: 0.4496 - val_mae: 0.4496
Epoch 3/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.4189 - mae: 0.4189 - val_loss: 0.3891 - val_mae: 0.3891
Epoch 4/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.3930 - mae: 0.3930 - val_loss: 0.3623 - val_mae: 0.3623
Epoch 5/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.3662 - mae: 0.3662 - val_loss: 0.4243 - val_mae: 0.4243
Epoch 6/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.3392 - mae: 0.3392 - val_loss: 0.3811 - val_mae: 0.3811
Epoch 7/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.3247 - mae: 0.3247 - val_loss: 0.3080 - val_mae: 0.3080
Epoch 8/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.3094 - mae: 0.3094 - val_loss: 0.3282 - val_mae: 0.3282
Epoch 9/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2899 - mae: 0.2899 - val_loss: 0.3375 - val_mae: 0.3375
Epoch 10/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2725 - mae: 0.2725 - val_loss: 0.3237 - val_mae: 0.3237
Epoch 11/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2539 - mae: 0.2539 - val_loss: 0.2621 - val_mae: 0.2621
Epoch 12/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2408 - mae: 0.2408 - val_loss: 0.2570 - val_mae: 0.2570
Epoch 13/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2338 - mae: 0.2338 - val_loss: 0.2760 - val_mae: 0.2760
Epoch 14/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2242 - mae: 0.2242 - val_loss: 0.2575 - val_mae: 0.2575
Epoch 15/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2131 - mae: 0.2131 - val_loss: 0.2333 - val_mae: 0.2333
Epoch 16/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2049 - mae: 0.2049 - val_loss: 0.2224 - val_mae: 0.2224
Epoch 17/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1959 - mae: 0.1959 - val_loss: 0.1913 - val_mae: 0.1913
Epoch 18/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1878 - mae: 0.1878 - val_loss: 0.1850 - val_mae: 0.1850
Epoch 19/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1873 - mae: 0.1873 - val_loss: 0.2112 - val_mae: 0.2112
Epoch 20/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1761 - mae: 0.1761 - val_loss: 0.1890 - val_mae: 0.1890
Epoch 21/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1689 - mae: 0.1689 - val_loss: 0.1913 - val_mae: 0.1913
Epoch 22/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1704 - mae: 0.1704 - val_loss: 0.1653 - val_mae: 0.1653
Epoch 23/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1552 - mae: 0.1552 - val_loss: 0.1760 - val_mae: 0.1760
Epoch 24/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1545 - mae: 0.1545 - val_loss: 0.2006 - val_mae: 0.2006
Epoch 25/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1527 - mae: 0.1527 - val_loss: 0.1556 - val_mae: 0.1556
Epoch 26/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1446 - mae: 0.1446 - val_loss: 0.1648 - val_mae: 0.1648
Epoch 27/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1379 - mae: 0.1379 - val_loss: 0.1169 - val_mae: 0.1169
Epoch 28/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1380 - mae: 0.1380 - val_loss: 0.1683 - val_mae: 0.1683
Epoch 29/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1293 - mae: 0.1293 - val_loss: 0.1664 - val_mae: 0.1664
Epoch 30/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1318 - mae: 0.1318 - val_loss: 0.1554 - val_mae: 0.1554
Epoch 31/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1235 - mae: 0.1235 - val_loss: 0.1045 - val_mae: 0.1045
Epoch 32/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1262 - mae: 0.1262 - val_loss: 0.1751 - val_mae: 0.1751
Epoch 33/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1220 - mae: 0.1220 - val_loss: 0.1244 - val_mae: 0.1244
Epoch 34/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1162 - mae: 0.1162 - val_loss: 0.1475 - val_mae: 0.1475
Epoch 35/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1124 - mae: 0.1124 - val_loss: 0.1331 - val_mae: 0.1331
Epoch 36/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1134 - mae: 0.1134 - val_loss: 0.1476 - val_mae: 0.1476
Epoch 37/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1078 - mae: 0.1078 - val_loss: 0.1236 - val_mae: 0.1236
Epoch 38/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1064 - mae: 0.1064 - val_loss: 0.1164 - val_mae: 0.1164
Epoch 39/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1033 - mae: 0.1033 - val_loss: 0.0976 - val_mae: 0.0976
Epoch 40/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0981 - mae: 0.0981 - val_loss: 0.1409 - val_mae: 0.1409
Epoch 41/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0983 - mae: 0.0983 - val_loss: 0.1151 - val_mae: 0.1151
Epoch 42/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0980 - mae: 0.0980 - val_loss: 0.1007 - val_mae: 0.1007
Epoch 43/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0946 - mae: 0.0946 - val_loss: 0.0972 - val_mae: 0.0972
Epoch 44/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0944 - mae: 0.0944 - val_loss: 0.0923 - val_mae: 0.0923
Epoch 45/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0893 - mae: 0.0893 - val_loss: 0.0972 - val_mae: 0.0972
Epoch 46/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0905 - mae: 0.0905 - val_loss: 0.0960 - val_mae: 0.0960
Epoch 47/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0871 - mae: 0.0871 - val_loss: 0.0978 - val_mae: 0.0978
Epoch 48/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0863 - mae: 0.0863 - val_loss: 0.0951 - val_mae: 0.0951
Epoch 49/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0843 - mae: 0.0843 - val_loss: 0.0771 - val_mae: 0.0771
Epoch 50/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0827 - mae: 0.0827 - val_loss: 0.0879 - val_mae: 0.0879
Epoch 51/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0797 - mae: 0.0797 - val_loss: 0.0742 - val_mae: 0.0742
Epoch 52/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0800 - mae: 0.0800 - val_loss: 0.0886 - val_mae: 0.0886
Epoch 53/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0786 - mae: 0.0786 - val_loss: 0.0905 - val_mae: 0.0905
Epoch 54/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0776 - mae: 0.0776 - val_loss: 0.0756 - val_mae: 0.0756
Epoch 55/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0744 - mae: 0.0744 - val_loss: 0.0676 - val_mae: 0.0676
Epoch 56/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0767 - mae: 0.0767 - val_loss: 0.0816 - val_mae: 0.0816
Epoch 57/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0715 - mae: 0.0715 - val_loss: 0.0676 - val_mae: 0.0676
Epoch 58/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0695 - mae: 0.0695 - val_loss: 0.0959 - val_mae: 0.0959
Epoch 59/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0709 - mae: 0.0709 - val_loss: 0.0787 - val_mae: 0.0787
Epoch 60/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0691 - mae: 0.0691 - val_loss: 0.0874 - val_mae: 0.0874
Epoch 61/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0662 - mae: 0.0662 - val_loss: 0.0607 - val_mae: 0.0607
Epoch 62/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0689 - mae: 0.0689 - val_loss: 0.0704 - val_mae: 0.0704
Epoch 63/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0666 - mae: 0.0666 - val_loss: 0.0718 - val_mae: 0.0718
Epoch 64/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0665 - mae: 0.0665 - val_loss: 0.0616 - val_mae: 0.0616
Epoch 65/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0652 - mae: 0.0652 - val_loss: 0.0660 - val_mae: 0.0660
Epoch 66/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0679 - mae: 0.0679 - val_loss: 0.0668 - val_mae: 0.0668
Epoch 67/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0607 - mae: 0.0607 - val_loss: 0.0610 - val_mae: 0.0610
Epoch 68/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0654 - mae: 0.0654 - val_loss: 0.0569 - val_mae: 0.0569
Epoch 69/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0634 - mae: 0.0634 - val_loss: 0.0540 - val_mae: 0.0540
Epoch 70/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0607 - mae: 0.0607 - val_loss: 0.0816 - val_mae: 0.0816
Epoch 71/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0594 - mae: 0.0594 - val_loss: 0.0735 - val_mae: 0.0735
Epoch 72/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0591 - mae: 0.0591 - val_loss: 0.0617 - val_mae: 0.0617
Epoch 73/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0594 - mae: 0.0594 - val_loss: 0.0622 - val_mae: 0.0622
Epoch 74/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0595 - mae: 0.0595 - val_loss: 0.0654 - val_mae: 0.0654
Epoch 75/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0564 - mae: 0.0564 - val_loss: 0.0691 - val_mae: 0.0691
Epoch 76/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0565 - mae: 0.0565 - val_loss: 0.0470 - val_mae: 0.0470
Epoch 77/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0581 - mae: 0.0581 - val_loss: 0.0762 - val_mae: 0.0762
Epoch 78/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0544 - mae: 0.0544 - val_loss: 0.0667 - val_mae: 0.0667
Epoch 79/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0531 - mae: 0.0531 - val_loss: 0.0583 - val_mae: 0.0583
Epoch 80/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0552 - mae: 0.0552 - val_loss: 0.0814 - val_mae: 0.0814
Epoch 81/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0520 - mae: 0.0520 - val_loss: 0.0564 - val_mae: 0.0564
Epoch 82/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0534 - mae: 0.0534 - val_loss: 0.0812 - val_mae: 0.0812
Epoch 83/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0533 - mae: 0.0533 - val_loss: 0.0525 - val_mae: 0.0525
Epoch 84/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0513 - mae: 0.0513 - val_loss: 0.0524 - val_mae: 0.0524
Epoch 85/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0527 - mae: 0.0527 - val_loss: 0.0537 - val_mae: 0.0537
Epoch 86/100000
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0512 - mae: 0.0512 - val_loss: 0.0670 - val_mae: 0.0670

In [116]:
y_pred = model.predict(X_test)
r2_score(y_test,y_pred)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

0.9287543575512114

In [146]:
#Prediccion de otro valor
df_destruction_pred = pd.read_csv("destruccion_empleo.csv")
df_destruction_pred.drop(columns=["quarter_label", "iso3_code","data_source_notes", "record_id","pct_sector_workforce_displaced"], inplace=True)

In [147]:
df_destruction_pred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       20800 non-null  object
 1   region                        20800 non-null  object
 2   income_group                  20800 non-null  object
 3   year                          20800 non-null  int64
 4   quarter                       20800 non-null  int64
 5   industry_sector               20800 non-null  object
 6   sector_automation_risk_score  20800 non-null  float64
 7   gdp_per_capita_usd            20800 non-null  int64
dtypes: float64(1), int64(3), object(4)
memory usage: 1.3+ MB

In [148]:
df_destruction_pred.head()

,country,region,income_group,year,quarter,industry_sector,sector_automation_risk_score,gdp_per_capita_usd
0,United States,North America,High Income,2020,1,Technology & Software,0.382,63514
1,United States,North America,High Income,2020,1,Finance & Banking,0.608,63514
2,United States,North America,High Income,2020,1,Healthcare & Life Sciences,0.198,63514
3,United States,North America,High Income,2020,1,Manufacturing & Industry,0.720,63514
4,United States,North America,High Income,2020,1,Retail & E-Commerce,0.676,63514

In [149]:
df_destruction_pred["year"][0] = 2027 
df_destruction_pred['quarter'][0] = 4
df_destruction_pred['industry_sector'][0] = 'Technology & Software'

/tmp/ipykernel_20491/1406139506.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_destruction_pred["year"][0] = 2027
/tmp/ipykernel_20491/1406139506.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_destruction_pred["year"][0] = 2027
/tmp/ipykernel_20491/1406139506.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_destruction_pred['quarter'][0] = 4
/tmp/ipykernel_20491/1406139506.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_destruction_pred['quarter'][0] = 4
/tmp/ipykernel_20491/1406139506.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_destruction_pred['industry_sector'][0] = 'Technology & Software'
/tmp/ipykernel_20491/1406139506.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_destruction_pred['industry_sector'][0] = 'Technology & Software'

In [150]:
df_destruction_pred = pd.get_dummies(df_destruction_pred,dtype=int)

In [151]:
df_destruction_pred.shape

(20800, 110)

In [152]:
X_prediction = scaler.fit_transform(df_destruction_pred)

In [ ]:
#He tratado de limpiarlo lo maximo posible para hacer que la prediccion sea posible, pero no logro obtener un resultado :(
y_pred = model.predict(X_prediction[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

# EJERCICIO 2

### Prueba 1

In [10]:
folder = listdir('DeFungi')
len(folder)
photos = []
labels = []

In [11]:
for idx, img in enumerate(folder):
    photo = load_img('DeFungi/'+img, color_mode='grayscale',target_size=(40,40))
    photo = img_to_array(photo)
    photos.append(photo)
    img_split = img.split('_')
    img_idx_clean = img_split[0].replace('H','')
    labels.append(float(img_idx_clean))

In [12]:
photos = asarray(photos).astype('float32') /255
labels = asarray(labels).astype('float32')

In [13]:
X_train, X_test, y_train, y_test = train_test_split(photos, labels, test_size=0.2, random_state=42)

In [14]:
X_train.shape

(7291, 40, 40, 1)

In [24]:
pd.Series(y_train).unique()

array([2., 1., 5., 3., 6.], dtype=float32)

In [18]:
model = keras.models.Sequential()
model.add(keras.layers.Conv2D(16,(3,3),activation='relu' ,input_shape=X_train.shape[1:]))
model.add(keras.layers.MaxPool2D(2,2))
model.add(keras.layers.Conv2D(32,(3,3), activation='relu'))
model.add(keras.layers.MaxPool2D(2,2))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(200,activation='relu' ,kernel_initializer='he_normal'))
model.add(keras.layers.Dense(40,activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.Dense(5, activation='softmax' ,kernel_initializer='glorot_normal'))

In [19]:
early_stopping_cb = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
model.compile(loss='categorical_crossentropy', metrics=['accuracy'],optimizer = keras.optimizers.Adam(learning_rate=0.0001,beta_1=0.9,beta_2=0.999))
history = model.fit(X_train, y_train, epochs=100000, validation_split = 0.1, callbacks=[early_stopping_cb])

Epoch 1/100000

ValueError: Arguments `target` and `output` must have the same rank (ndim). Received: target.shape=(None,), output.shape=(None, 5)

In [ ]:
model.evaluate(X_test,y_test)

### Prueba 2

In [4]:
folder = listdir('DeFungi')
len(folder)
photos = []
labels = []

In [ ]:
for idx, img in enumerate(folder):
    photo = load_img('DeFungi/'+img, color_mode='grayscale')
    photo = img_to_array(photo)
    photos.append(photo)
    img_split = img.split('_')
    img_idx_clean = img_split[0].replace('H','')
    img_idx_clean = img_idx_clean.replace({'1': '0', '2': '1', '3': '2', '5': '3', '6': '4'})
    labels.append(float(img_idx_clean))

In [6]:
photos = asarray(photos).astype('float32') /255
labels = asarray(labels).astype('float32')

In [7]:
X_train, X_test, y_train, y_test = train_test_split(photos, labels, test_size=0.2, random_state=42)

In [8]:
model = keras.models.Sequential()
model.add(keras.layers.Conv2D(16,(3,3),activation='relu' ,input_shape=X_train.shape[1:]))
model.add(keras.layers.MaxPool2D(2,2))
model.add(keras.layers.Conv2D(32,(3,3), activation='relu'))
model.add(keras.layers.MaxPool2D(2,2))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(200,activation='relu' ,kernel_initializer='he_normal'))
model.add(keras.layers.Dense(40,activation='relu', kernel_initializer='he_normal'))
model.add(keras.layers.Dense(6, activation='softmax' ,kernel_initializer='glorot_normal'))

/home/ciabd12/anaconda3/lib/python3.13/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
W0000 00:00:1778522777.549327   84050 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

In [9]:
early_stopping_cb = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
model.compile(loss='categorical_crossentropy', metrics=['accuracy'],optimizer = keras.optimizers.Adam(learning_rate=0.0001,beta_1=0.9,beta_2=0.999))
history = model.fit(X_train, y_train, epochs=100000, validation_split = 0.1, callbacks=[early_stopping_cb])

Epoch 1/100000

ValueError: Arguments `target` and `output` must have the same rank (ndim). Received: target.shape=(None,), output.shape=(None, 6)

- No he logrado entrenar pero imagino que la diferencia entre los 2 casos sea que en una al hacer las imagenes mas pequeñas, habra que usar menos capas de pooling para que no desaparezca la imagen y meter menos en la de salida, y en la otra cogiendo menos imagenes pero con mas dimensión habría que reajustar