## Actividad 3_11

<div style="border-style:groove;border-width:thin;padding:10px">

Trabajamos en una empresa de alquiler de bicicletas en Seul. El departamento de mantenimiento de bicicletas ha pedido a nuestro departamento de DataScience si es posible poder saber, a priori, cuantas bicicletas tiene que haber disponibles porque ellos tienen que ir retirando bicicletas para repararlas. Tenemos los datos que se muestran a continuación. ¿Será posible saber cuantas tienen que tener en circulación?

</div>

In [1]:
from sklearn.datasets import make_moons
from sklearn.tree import DecisionTreeRegressor
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.tree import export_graphviz
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error, mean_absolute_error, r2_score

In [2]:
import pandas as pd
df_bikes = pd.read_csv("SeoulBikeData.csv", sep=',',encoding='latin-1')
df_bikes.head()

         Date  Rented Bike Count  Hour  ...  Seasons     Holiday  Functioning Day
0  01/12/2017                254     0  ...   Winter  No Holiday              Yes
1  01/12/2017                204     1  ...   Winter  No Holiday              Yes
2  01/12/2017                173     2  ...   Winter  No Holiday              Yes
3  01/12/2017                107     3  ...   Winter  No Holiday              Yes
4  01/12/2017                 78     4  ...   Winter  No Holiday              Yes

[5 rows x 14 columns]

In [3]:
df_bikes.drop(columns=["Date"], axis=1, inplace=True)
df_bikes = pd.get_dummies(df_bikes, columns=["Seasons", "Holiday", "Functioning Day"], dtype=int)

In [4]:
df_bikes.head()

   Rented Bike Count  Hour  ...  Functioning Day_No  Functioning Day_Yes
0                254     0  ...                   0                    1
1                204     1  ...                   0                    1
2                173     2  ...                   0                    1
3                107     3  ...                   0                    1
4                 78     4  ...                   0                    1

[5 rows x 18 columns]

In [5]:
df_bikes.corr(numeric_only=True)['Rented Bike Count'].abs().sort_values(ascending=False)[1:]

Temperature(°C)              0.538558
Seasons_Winter               0.424925
Hour                         0.410257
Dew point temperature(°C)    0.379788
Seasons_Summer               0.296549
Solar Radiation (MJ/m2)      0.261837
Functioning Day_No           0.203943
Functioning Day_Yes          0.203943
Humidity(%)                  0.199780
Visibility (10m)             0.199280
Snowfall (cm)                0.141804
Rainfall(mm)                 0.123074
Wind speed (m/s)             0.121108
Seasons_Autumn               0.102753
Holiday_Holiday              0.072338
Holiday_No Holiday           0.072338
Seasons_Spring               0.022888
Name: Rented Bike Count, dtype: float64

In [6]:
#Generamos los conjuntos X e y.
X = df_bikes.drop(['Rented Bike Count'],axis=1)
y = df_bikes['Rented Bike Count'].to_frame()

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [ ]:
tree_clf = DecisionTreeRegressor(max_depth=9, min_samples_leaf=2, min_samples_split=20)
tree_clf.fit(X_train, y_train)

# For a regressor there is no `classes_` attribute, so omit `class_names`.
export_graphviz(
    tree_clf,
    out_file="./seul_bike.dot",
    feature_names=list(df_bikes.drop(['Rented Bike Count'], axis=1).columns),
    rounded=True,
    filled=True
)

# If "dot: command not found" occurs, install graphviz in the system:
# sudo apt install graphviz
!dot -Tpng seul_bike.dot -o seul_bike.png

In [12]:
y_pred = tree_clf.predict(X_test)
print(y_pred)
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("R^2 Score:", tree_clf.score(X_test, y_test))
print("Mean Squared Error:", mean_squared_error(y_test,y_pred))

[1357.11538462  670.85294118  670.85294118 ... 1357.11538462   51.03448276
  468.90909091]
Mean Absolute Error: 181.11883298200544
R^2 Score: 0.7924965771624605
Mean Squared Error: 84910.60464120934